FROM cern/slc6-base:20170301

MAINTAINER Stefan Geißelsöder <stefan.geisselsoeder@fau.de>

# everything is in one command to avoid itnermediate layers (saves space)
#RUN yum -y install centos-release-scl && \
RUN mkdir -p /input && mkdir -p /output && \
    yum -y update && \
    yum -y upgrade && \
    yum -y install --setopt=tsflags=nodocs \
    automake \
    autoconf \
    bash \
    cvs \
    gcc \
    gcc-c++ \
    git \
    make \
    subversion \
    boost \
    libstdc++ \ 
    bison \
    zip \
    unzip \
    wget \
    bzip2 \
    binutils \
    python \
    redhat-lsb-core \
    gcc-gfortran \ 
    openssl-devel \ 
    pcre-devel \ 
    libX11-devel libXpm-devel libXft-devel libXext-devel \
    make gcc gcc-c++ gcc-gfortran \
    cmake zlib-devel\
    openmpi openmpi-devel \
    fftw fftw-devel \
    gsl gsl-devel gmp \
    python-devel \
    docutils python-nose \
    python-docutils \
    lzo-devel \ 
    bzip2-devel \
    tkinter \
    csh ghostscript ant bison \
    fftw-devel flex flex-devel gcc gcc-c++ gcc-gfortran gdb git glibc-static gtk2-devel gzip \
    libgpg-error libproxy libX11 libX11-common libX11-devel libXext libXext-devel \
    libXft libXft-devel libXpm libXpm-devel make openssh-server pakchois \
    python-devel subversion tar vim wget zsh 

RUN yum install -y tcl-devel 
# RUN yum groupinstall -y "X Software Development" 
RUN yum groupinstall -y "X Window System" 
RUN yum groupinstall -y "CERN Addons X11" 
RUN yum install -y xorg-x11-server-devel
RUN yum groupinstall -y "Desktop Platform Development"

# RUN yum -y install x11vnc firefox xorg-x11-fonts* xorg-x11-xinit xorg-x11-xinit-session xorg-x11-server-Xvfb xorg-x11-twm tigervnc-server xterm xorg-x11-font

RUN svn checkout --non-interactive --no-auth-cache --username km3net --password default-km3net-read-pw http://svn.km3net.physik.uni-erlangen.de/tools/DarwinPorts/trunk ~/port_source 
# RUN mkdir /i3ports
RUN yum install -y ncurses-devel

RUN yum install -y uuid-devel uuid-c++.x86_64 uuid-c++-devel.x86_64 libuuid-devel.x86_64 pkgconfig libtool gcc-c++ libuuid-devel

COPY hotfixes /hotfixes
RUN cp /hotfixes/i3-install.sh /root/port_source/ && chmod 755 /root/port_source/i3-install.sh


# vim /i3ports/var/db/dports/sources/rsync.code.km3net.physik.uni-erlangen.de_icetray-tools-ports/science/igraph_0.5.4/Portfile
# https://downloads.sourceforge.net/project/igraph/C%20library/0.5.4/igraph-0.5.4.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Figraph%2Ffiles%2FC%2520library%2F0.5.4%2F&ts=1494922614&use_mirror=netcologne
# cd /i3ports
# ./bin/port install i3-tools-km3net-v4
RUN ls /hotfixes && env && cd ~/port_source && export I3_PORTS=/i3ports && env ./i3-install.sh $I3_PORTS && env

ENV I3_PORTS /i3ports

RUN yum install -y scipy numpy

RUN env && mkdir /seatray && cd /seatray && svn checkout --non-interactive --no-auth-cache --username km3net --password default-km3net-read-pw http://svn.km3net.physik.uni-erlangen.de/icetray/meta-projects/searec/trunk src && mkdir build
RUN cd /seatray && mv src/grb-shower . && mv src/antares-tantra-reco . && mv src/antares-antdst-writer . 

#RUN cd /seatray/build && pwd && ${I3_PORTS}/bin/cmake ../src
RUN cd /seatray/build && pwd && ${I3_PORTS}/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug ../src

RUN cd /seatray/build && make

ENTRYPOINT ["/bin/bash"]
