FROM cern/slc6-base:20170301

MAINTAINER Stefan Geißelsöder <stefan.geisselsoeder@fau.de>

# everything is in one command to avoid itnermediate layers (saves space)
#RUN yum -y install centos-release-scl && \
RUN mkdir -p /input && mkdir -p /output && \
    yum -y update && \
    yum -y upgrade && \
    yum -y install --setopt=tsflags=nodocs \
    automake \
    autoconf \
    bash \
    cvs \
    gcc \
    gcc-c++ \
    git \
    make \
    subversion \
    boost \
    libstdc++ \ 
    bison \
    zip \
    unzip \
    wget \
    bzip2 \
    binutils \
    python \
    redhat-lsb-core \
    gcc-gfortran \ 
    openssl-devel \ 
    pcre-devel \ 
    libX11-devel libXpm-devel libXft-devel libXext-devel \
    make gcc gcc-c++ gcc-gfortran \
    cmake zlib-devel\
    openmpi openmpi-devel \
    fftw fftw-devel \
    gsl gsl-devel gmp \
    python-devel \
    docutils python-nose \
    python-docutils \
    lzo-devel \ 
    bzip2-devel \
    tkinter \
    csh ghostscript ant bison \
    fftw-devel flex flex-devel gcc gcc-c++ gcc-gfortran gdb git glibc-static gtk2-devel gzip \
    libgpg-error libproxy libX11 libX11-common libX11-devel libXext libXext-devel \
    libXft libXft-devel libXpm libXpm-devel make openssh-server pakchois \
    python-devel subversion tar vim wget zsh \
    tcl-devel ncurses-devel \
    uuid-devel uuid-c++.x86_64 uuid-c++-devel.x86_64 libuuid-devel.x86_64 pkgconfig libtool gcc-c++ libuuid-devel \
    xorg-x11-server-devel \
    scipy numpy

RUN yum groupinstall -y "Desktop Platform Development"

COPY hotfixes /hotfixes
ENV I3_PORTS /i3ports

# I3_PORTS
RUN svn checkout --non-interactive --no-auth-cache --username km3net --password common-read-pw \ 
    http://svn.km3net.physik.uni-erlangen.de/tools/DarwinPorts/trunk ~/port_source && \
    cp /hotfixes/i3-install.sh /root/port_source/ && chmod 755 /root/port_source/i3-install.sh && \
    cd ~/port_source && ./i3-install.sh /i3ports 

# SEATRAY
RUN mkdir /seatray && cd /seatray && svn checkout --non-interactive --no-auth-cache --username km3net --password common-read-pw \
    http://svn.km3net.physik.uni-erlangen.de/icetray/meta-projects/searec/trunk src && mkdir build && \
    mv src/grb-shower . && mv src/antares-tantra-reco . && mv src/antares-antdst-writer . && \ 
    cd build && ${I3_PORTS}/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Release ../src && make

ENTRYPOINT ["/bin/bash"]
