FROM centos:latest

MAINTAINER Stefan Geißelsöder <stefan.geisselsoeder@fau.de>

# everything is in one command to avoid itnermediate layers (saves space)
#RUN yum -y install centos-release-scl && \
RUN mkdir -p /input && mkdir -p /output && \
    yum -y update && \
    yum -y upgrade && \
    yum -y install --setopt=tsflags=nodocs \
    automake \
    autoconf \
    bash \
    cvs \
    gcc \
    gcc-c++ \
    git \
    make \
    subversion \
    boost \
    libstdc++ \ 
    bison \
    zip \
    unzip \
    wget \
    bzip2 \
    binutils \
    python \
    redhat-lsb-core \
    gcc-gfortran \ 
    openssl-devel \ 
    pcre-devel \ 
    libX11-devel libXpm-devel libXft-devel libXext-devel \
    make gcc gcc-c++ gcc-gfortran \
    cmake zlib-devel\
    openmpi openmpi-devel \
    fftw fftw-devel \
    gsl gsl-devel gmp \
    python-devel \
    docutils python-nose \
    python-docutils \
    lzo-devel \ 
    bzip2-devel \
    tkinter \
    csh ghostscript ant bison bzip2-devel \
    fftw-devel flex flex-devel gcc gcc-c++ gcc-gfortran gdb git glibc-static gtk2-devel gzip \
    libgpg-error libproxy libX11 libX11-common libX11-devel libXext libXext-devel \
    libXft libXft-devel libXpm libXpm-devel make openssh-server pakchois \
    python-devel subversion tar vim wget zsh \
    && yum -y remove python-setuptools && \ 
    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && \ 
    python get-pip.py && rm get-pip.py && \
    pip install cython numpy h5py setuptools scipy tables matplotlib && \
    pip install km3pipe && \
    yum -y clean all 
# devtoolset-4-gcc* \
# python-numpy-devel gsl-static hdf5 hdf5-devel lbzip2 blosc blosc-devel openjdk-8-jdk CLBSwissKnife cmake28 compat-gcc-34-g77

# let's go for ROOT
RUN mkdir /tmp/root -p && cd /tmp/root/ && \
    wget https://root.cern.ch/download/root_v5.34.36.source.tar.gz && \
    tar xf root_v5.34.36.source.tar.gz && \ 
    cd root && \
    ./configure linuxx8664gcc --enable-python --prefix=/usr/local && \
    make -j 2 ; make -j 2 ; make -j 2 ; make -j 2 && \
    make install && \
    cd / && \
    rm -rf /tmp/root 
ENV ROOTSYS /usr/local
ENV LD_LIBRARY_PATH /usr/local/lib/root
ENV LIBPATH /usr/local/lib/root
ENV DYLD_LIBRARY_PATH /usr/local/lib/root
ENV PYTHONPATH /usr/local/lib/root
ENV SHLIB_PATH /usr/local/lib/root

# Install jpp
COPY externalResources/JDAQUTCExtended.hh /
RUN svn checkout --non-interactive --no-auth-cache --username km3net --password pyrosoma http://svn.km3net.de/Jpp/tag/v7.1.6632/ /jpp && \
    mv /JDAQUTCExtended.hh /jpp/software/JDAQ/JDAQUTCExtended.hh && \
    cd /jpp && source ./setenv.sh && make -j 2 ; make -j 2 ; make -j 2 ; make Antares ; make KM3NeT ; make libs

# (sic!)
ENV AANET_DIR /jpp/externals/aanet/
ENV JPP_DATA /jpp/data/
ENV JDB_DIR /jpp/externals/dbclient/
ENV LD_LIBRARY_PATH /jpp/externals/aanet/:/jpp/out//Linux/lib/:/jpp/externals/dbclient//lib/:/usr/local/lib/root
ENV AA_CONVERT_G3 1
ENV PATH /jpp/externals/aanet/:/jpp/out//Linux/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV AADIR /jpp/externals/aanet/
ENV JPP_BIN /jpp/out//Linux/bin/
ENV CHSM_DIR /jpp/externals/chsm/
ENV AANET_LIB /jpp/externals/aanet/
ENV TIMER 0
ENV PYTHONPATH /jpp/externals/aanet/:/usr/local/lib/root
ENV SYSTEM Linux
ENV PROCESSOR x86_64
ENV MACHINE x86_64
ENV JPP_DIR /jpp
ENV JPP_OUT /jpp/out/
ENV JDB_LIB /jpp/externals/dbclient//lib/
ENV JPP_DOC /jpp/doc/
ENV DEBUG 0
ENV JPP_LIB /jpp/out//Linux/lib/

ENTRYPOINT ["/bin/bash"]
